version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/css-inline" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/c" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/python" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/ruby" 
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/wasm" 
    schedule:
      interval: "daily"
