name: "[C] Release"

on:
  push:
    tags:
      - c-v*

jobs:
  ruby-release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release
        working-directory: ./bindings/c

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bindings/c/target/release/libcss_inline.so
            bindings/c/css_inline.h
